version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # - "/home/kozlovjr/devops-for-programmers-project-74/app:/app"
      - "./app:/app"