name: image-test

on: push 

jobs:
  image-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make ci
      - run: docker-compose -f docker-compose.yml build app
      - run: docker-compose -f docker-compose.yml push app